name: nuntius
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.2.3 # NOVA DEPENDÊNCIA ADICIONADA AQUI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Adicione esta linha para incluir todas as imagens nesta pasta